name: Update CKB client versions

on:
  push

jobs:
  default:
    name: Update CKB client versions
    runs-on: ubuntu-latest
    environment: neuron-bot
    permissions:
      pull-requests: write # open PR
      contents: write # update version files

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.1

      - name: Update versions
        id: update_versions
        run: |
          npm run update:client-versions
          git add .ckb-version .ckb-light-version compatible.json

      - name: Open PR to develop branch
        uses: peter-evans/create-pull-request@v6
        with:
          title: Update ckb client versions
          commit-message: 'feat: update ckb client versions'
          body: 'Update versions of builtin CKB node and light client'
          branch: update-ckb-client-versions
